FROM ruby:3.3.6-slim

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    GEM_HOME=/usr/local/bundle \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_APP_CONFIG=/usr/local/bundle \
    PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/bin:$PATH

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    curl \
    libpq-dev \
    pkg-config \
    libvips \
    postgresql-client && \
    gem install rails -v 7.2.3 --bindir /usr/local/bin --no-document && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD ["bash"]